const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),rx=require('rxjs'),{randomUUID}=require('node:crypto');
function setup(){
 const requests=[],effects=[],deps={AuthService:{isPrivileged:()=>true,hasPermission:()=>true,currentUser:()=>({})},OrganizationContextService:{selectedOrganizationId:()=>'org',getActiveOrganizationId:()=>'org'}};
 deps.ApiService=new Proxy({},{get:(_,method)=>(url,body)=>{const stream=new rx.Subject();requests.push({method,url,body,stream});return stream;}});
 const source=ts.transpileModule(fs.readFileSync(require.resolve('../src/app/pages/cheques-page/cheques-page.component.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,experimentalDecorators:true}}).outputText;
 const module={exports:{}};vm.runInNewContext(source,{module,exports:module.exports,Date,Intl,URLSearchParams,crypto:{randomUUID},require(name){if(name==='rxjs')return rx;if(name==='@angular/core')return{Component:()=>v=>v,inject:k=>deps[k],effect:fn=>effects.push(fn)};return new Proxy({},{get:(_,k)=>k});}});
 const page=new module.exports.ChequesPageComponent();page.accounts=[{id:'a',name:'Operating',currency:'PHP',balance:'100.00',isArchived:false}];
 const row={id:'c',accountId:'a',number:'001',payee:'Supplier',amount:'25.10',currency:'PHP',status:'issued',datedOn:'2026-01-02',clearedOn:'2026-01-03'};
 return{page,row,requests,effects,deps};
}
test('issuance validates amounts, bank status and cheque dates',()=>{const{page}=setup();page.openIssue();Object.assign(page.draft,{number:'001',payee:'Supplier',amount:'1.25'});assert.equal(page.valid,true);for(const amount of ['0','-1','1.001','NaN']){page.draft.amount=amount;assert.equal(page.valid,false);}page.draft.amount='1.25';page.draft.datedOn='2000-01-01';assert.equal(page.valid,false);page.draft.datedOn='2999-01-01';assert.equal(page.valid,true);page.accounts[0].isArchived=true;assert.equal(page.valid,false);});
test('double submit is prevented and issue retries retain the request key',()=>{const{page,requests}=setup();page.openIssue();Object.assign(page.draft,{number:'001',payee:'Supplier',amount:'1.25'});page.save();page.save();assert.equal(requests.length,1);const key=requests[0].body.requestKey;requests[0].stream.error({error:{message:'Try again'}});page.save();assert.equal(requests[1].body.requestKey,key);requests[1].stream.next({message:'Saved'});assert.equal(page.modal,'');assert.equal(page.notice,'Saved');assert.equal(requests[2].method,'getFresh');});
test('postdated and terminal cheques cannot open invalid clearance actions',()=>{const{page,row}=setup();page.open('clear',{...row,datedOn:'2999-01-01'});assert.equal(page.modal,'');page.open('clear',{...row,status:'void'});assert.equal(page.modal,'');page.open('clear',row);assert.equal(page.modal,'clear');page.postedOn='2026-01-01';assert.equal(page.validAction,false);page.postedOn='2999-01-01';assert.equal(page.validAction,false);});
test('bank returns require a reason and valid date; submit targets selected cheque',()=>{const{page,row,requests}=setup();page.open('return',{...row,status:'cleared'});page.save();assert.equal(requests.length,0);page.reason='Returned by bank';page.postedOn='2026-01-02';assert.equal(page.validAction,false);page.postedOn='2026-01-04';page.save();assert.match(requests[0].url,/cheques\/c\/actions/);assert.equal(requests[0].body.action,'return');});
test('organization switches cancel pending reads and writes and clear financial details',()=>{const{page,row,requests,effects}=setup();page.load();page.open('clear',row);page.save();effects[0]();for(const r of requests.slice(0,3))assert.equal(r.stream.observers.length,0);assert.equal(page.selected,null);assert.equal(page.rows.length,0);assert.equal(page.modal,'');page.ngOnDestroy();for(const r of requests)assert.equal(r.stream.observers.length,0);});
test('non-administrators with bank permissions cannot read or change cheques',()=>{const{page,row,requests,deps}=setup();deps.AuthService.isPrivileged=()=>false;page.load();page.openIssue();page.open('clear',row);page.save();assert.equal(requests.length,0);assert.equal(page.modal,'');});
