const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),rx=require('rxjs'),{randomUUID}=require('node:crypto');
function setup(){
 const requests=[],effects=[],deps={AuthService:{isPrivileged:()=>true,hasPermission:()=>true,currentUser:()=>({})},OrganizationContextService:{selectedOrganizationId:()=>'org',getActiveOrganizationId:()=>'org'}};
 deps.ApiService=new Proxy({},{get:(_,method)=>(url,body)=>{const stream=new rx.Subject();requests.push({method,url,body,stream});return stream;}});
 const source=ts.transpileModule(fs.readFileSync(require.resolve('../src/app/pages/vouchers-page/vouchers-page.component.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,experimentalDecorators:true}}).outputText;
 const module={exports:{}};vm.runInNewContext(source,{module,exports:module.exports,Date,Intl,URLSearchParams,crypto:{randomUUID},require(name){if(name==='rxjs')return rx;if(name==='@angular/core')return{Component:()=>v=>v,inject:k=>deps[k],effect:fn=>effects.push(fn)};return new Proxy({},{get:(_,k)=>k});}});
 const page=new module.exports.VouchersPageComponent();page.accounts=[{id:'a',name:'Operating',currency:'PHP',balance:'100.00',isArchived:false}];
 const row={id:'c',accountId:'a',number:'001',payee:'Supplier',amount:'25.10',currency:'PHP',status:'posted',postedOn:'2026-01-02'};
 return{page,row,requests,effects,deps};
}
test('voucher validation requires payment details and prevents invalid or unfunded amounts',()=>{const{page}=setup();page.openCreate();Object.assign(page.draft,{payee:'Supplier',description:'Supplies',amount:'25.10'});assert.equal(page.valid,true);for(const amount of ['0','-1','1.001','100.01','NaN']){page.draft.amount=amount;assert.equal(page.valid,false);}page.draft.amount='100.00';assert.equal(page.valid,true);page.draft.postedOn='2999-01-01';assert.equal(page.valid,false);page.draft.postedOn=page.today();page.accounts[0].isArchived=true;assert.equal(page.valid,false);});
test('double click cannot post twice and failed submission retains the same request key',()=>{const{page,requests}=setup();page.openCreate();Object.assign(page.draft,{payee:'Supplier',description:'Supplies',amount:'25.10'});page.save();page.save();assert.equal(requests.length,1);const key=requests[0].body.requestKey;requests[0].stream.error({error:{message:'Retry'}});assert.equal(page.formError,'Retry');page.save();assert.equal(requests[1].body.requestKey,key);requests[1].stream.next({message:'Saved'});assert.equal(page.modal,'');assert.equal(requests[2].method,'getFresh');});
test('void requires a reason and date not before posting and sends the selected voucher',()=>{const{page,row,requests}=setup();page.openVoid(row);page.save();assert.equal(requests.length,0);page.reason='Correction';page.voidedOn='2026-01-01';assert.equal(page.validVoid,false);page.voidedOn='2026-01-03';page.save();assert.match(requests[0].url,/vouchers\/c\/void/);assert.equal(requests[0].body.reason,'Correction');});
test('organization changes cancel outstanding reads and writes and clear voucher state',()=>{const{page,row,requests,effects}=setup();page.load();page.openVoid(row);page.reason='Correction';page.save();effects[0]();for(const r of requests.slice(0,3))assert.equal(r.stream.observers.length,0);assert.equal(page.selected,null);assert.equal(page.modal,'');page.ngOnDestroy();for(const r of requests)assert.equal(r.stream.observers.length,0);});
test('nonadministrators cannot load, create or void vouchers even with bank permissions',()=>{const{page,row,requests,deps}=setup();deps.AuthService.isPrivileged=()=>false;page.load();page.openCreate();page.openVoid(row);page.save();assert.equal(requests.length,0);assert.equal(page.modal,'');});
