import { CrudResourceConfig } from '../core/types';

export const RESOURCE_CONFIGS: Record<string, CrudResourceConfig> = {
  organizations: {
    title: 'Organizations',
    endpoint: '/api/v1/organizations',
    summaryFields: ['name', 'contactEmail', 'phone', 'city', 'isActive'],
    fields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'legalName', label: 'Legal Name' },
      { key: 'taxId', label: 'Tax ID' },
      { key: 'addressLine1', label: 'Address Line 1', required: true },
      { key: 'addressLine2', label: 'Address Line 2' },
      { key: 'city', label: 'City', required: true },
      { key: 'state', label: 'State' },
      { key: 'postalCode', label: 'Postal Code' },
      { key: 'country', label: 'Country', required: true, placeholder: 'United States' },
      { key: 'contactName', label: 'Contact Name' },
      { key: 'contactEmail', label: 'Contact Email', type: 'email', required: true },
      { key: 'phone', label: 'Phone', required: true },
      { key: 'website', label: 'Website' },
      { key: 'industry', label: 'Industry' },
      { key: 'employeeCount', label: 'Employee Count', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    createDefaults: { isActive: true, country: 'United States' },
  },
  users: {
    title: 'Users',
    endpoint: '/api/v1/users',
    summaryFields: ['firstName', 'lastName', 'email', 'status', 'isActive'],
    fields: [
      { key: 'organizationId', label: 'Organization ID' },
      { key: 'firstName', label: 'First Name', required: true },
      { key: 'lastName', label: 'Last Name', required: true },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'password', label: 'Password' },
      { key: 'phone', label: 'Phone' },
      { key: 'addressLine1', label: 'Address Line 1' },
      { key: 'addressLine2', label: 'Address Line 2' },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
      { key: 'postalCode', label: 'Postal Code' },
      { key: 'country', label: 'Country' },
      { key: 'role', label: 'Role' },
      { key: 'status', label: 'Status' },
      { key: 'isEmailVerified', label: 'Email Verified', type: 'checkbox' },
      { key: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    createDefaults: { status: 'pending_verification', isEmailVerified: false, isActive: true },
  },
  roles: {
    title: 'Roles',
    endpoint: '/api/v1/roles',
    summaryFields: ['name', 'code', 'isSystem', 'isActive'],
    fields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'code', label: 'Code', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'isSystem', label: 'System Role', type: 'checkbox' },
      { key: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    createDefaults: { isSystem: false, isActive: true },
  },
  permissions: {
    title: 'Permissions',
    endpoint: '/api/v1/permissions',
    summaryFields: ['name', 'code', 'resource', 'action', 'isActive'],
    fields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'code', label: 'Code', required: true },
      { key: 'resource', label: 'Resource', required: true },
      { key: 'action', label: 'Action', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'isSystem', label: 'System Permission', type: 'checkbox' },
      { key: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    createDefaults: { isSystem: false, isActive: true },
  },
  items: {
    title: 'Items',
    endpoint: '/api/v1/items',
    summaryFields: ['name', 'type', 'sku', 'price', 'stock', 'isActive'],
    fields: [
      { key: 'organizationId', label: 'Organization ID', required: true },
      { key: 'type', label: 'Type' },
      { key: 'sku', label: 'SKU' },
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'category', label: 'Category' },
      { key: 'unit', label: 'Unit' },
      { key: 'price', label: 'Price', type: 'number' },
      { key: 'discountedPrice', label: 'Discounted Price', type: 'number' },
      { key: 'currency', label: 'Currency' },
      { key: 'stock', label: 'Stock', type: 'number' },
      { key: 'reorderLevel', label: 'Reorder Level', type: 'number' },
      { key: 'taxRate', label: 'Tax Rate', type: 'number' },
      { key: 'isActive', label: 'Active', type: 'checkbox' },
      { key: 'createdBy', label: 'Created By (User ID)' },
      { key: 'updatedBy', label: 'Updated By (User ID)' },
    ],
    createDefaults: { isActive: true, currency: 'USD', stock: 0 },
  },
  licenses: {
    title: 'Licenses',
    endpoint: '/api/v1/licenses',
    summaryFields: ['organizationId', 'key', 'planName', 'status', 'expiresAt'],
    fields: [
      { key: 'organizationId', label: 'Organization ID', required: true },
      { key: 'key', label: 'License Key', required: true },
      { key: 'planName', label: 'Plan Name' },
      { key: 'status', label: 'Status' },
      { key: 'startsAt', label: 'Starts At', type: 'datetime-local' },
      { key: 'expiresAt', label: 'Expires At', type: 'datetime-local', required: true },
      { key: 'maxUsers', label: 'Max Users', type: 'number' },
      { key: 'isActive', label: 'Active', type: 'checkbox' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    createDefaults: { status: 'active', isActive: true },
  },
  salesInvoices: {
    title: 'Sales Invoices',
    endpoint: '/api/v1/sales-invoices',
    summaryFields: ['invoiceNumber', 'organizationId', 'orderId', 'status', 'totalAmount'],
    fields: [
      { key: 'organizationId', label: 'Organization ID', required: true },
      { key: 'orderId', label: 'Order ID', required: true },
      { key: 'invoiceNumber', label: 'Invoice Number', required: true },
      { key: 'issueDate', label: 'Issue Date', type: 'date', required: true },
      { key: 'dueDate', label: 'Due Date', type: 'date' },
      { key: 'status', label: 'Status' },
      { key: 'paymentStatus', label: 'Payment Status' },
      { key: 'currency', label: 'Currency' },
      { key: 'subtotalAmount', label: 'Subtotal', type: 'number' },
      { key: 'taxAmount', label: 'Tax', type: 'number' },
      { key: 'discountAmount', label: 'Discount', type: 'number' },
      { key: 'totalAmount', label: 'Total', type: 'number' },
      { key: 'paidAt', label: 'Paid At', type: 'datetime-local' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'createdBy', label: 'Created By (User ID)' },
      { key: 'updatedBy', label: 'Updated By (User ID)' },
    ],
    createDefaults: { currency: 'USD', status: 'draft', paymentStatus: 'unpaid' },
  },
};
